CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512

# BLE: минимальная задержка с учётом допустимого диапазона
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# Буферы для пропускной способности
CONFIG_BT_BUF_ACL_TX_COUNT=48
CONFIG_BT_L2CAP_TX_BUF_COUNT=48

# Максимально возможная длина данных для контроллера
# CONFIG_BT_CTLR_DATA_LENGTH_MAX=69
CONFIG_BT_CTLR_DATA_LENGTH_MAX=250

# 2M PHY включать можно, если поддерживается (опционально)
#CONFIG_BT_CTLR_PHY_2M=y

# MTU чуть больше стандартного (опционально)
CONFIG_BT_L2CAP_TX_MTU=128

CONFIG_BT_MAX_CONN=4
CONFIG_BT_MAX_PAIRED=4





